### ISSUE TITLE
BUG: The type 'MemoryExtensions' exists in both assemblies in version 1.5

### ISSUE THREAD

**Issue by laicasaane** [draconware-dev/SpanExtensions.Net#25]
**Describe the bug**  
When I upgrade this library to v1.5 in a Unity project which uses .NET Standard 2.1, the compiler throws errors like this:

```
Error CS0433: The type 'MemoryExtensions' exists in both 'SpanExtensions.Net.Unity, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
```

**To Reproduce**  
I don't suppose you're using Unity so I will omit this part because this ultimately doesn't relate to Unity.

**Expected behavior**  
No compilation error.

**Version**  
v1.5

**Additional context**   
The type 'MemoryExtensions' already exists since .NET Standard 2.1, this define

```
#if !NET9_0_OR_GREATER
```

is not a good one.

**Comment by dragon7307** [comment]
Hey, thanks for your report. 

I've looked into this and tried to run Split on frameworks below .Net 9, which worked flawlessly.
I might need more information here, yet 
```
#if !NET9_0_OR_GREATER
```

should be (and in fact is as far as I can tell) fine, since MemoryExtensions is declared as a partial class in my source as well as in the CoreCLR as provided by Microsoft. 

You mentioned that you are running .Net Standard 2.1, which is not really a possibility as .Net Standard is only a specification and not a concrete implemention of .Net unlike .Net Core. From the little Unity experience I have, I seem to recall that Unity provides its own .Net Standard 2.1 compliant runtime, which presumably is what you are refering to.

I currently assume, unless you have evidence to the contrary, that this is a compatibility issue with Unity's implementation and not a flaw of the package I can fix. 

**However, as I see you are providing a fork for unity, perhaps try changing the namespace of MemoryExtensions in `src/Enumerators/System/SpanSplitEnumerator.cs` from `System` to `SpanExtensions` and see if that helps.**

**Comment by laicasaane** [comment]
Yes changing namespace or type name is doable. However it might introduce incompatibility which complicate the updating process. However, I will go this route then.

> MemoryExtensions is declared as a partial class in my source as well as in the CoreCLR as provided by Microsoft

Stated in the document: [Partial definitions can't span multiple modules.](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods#:~:text=Partial%20definitions%20can%27t%20span%20multiple%20modules.)

**Comment by dragon7307** [comment]
You're right, I'm somewhat confused why it doesn't break then on earlier .Net versions (like .Net 7/8) as it should, yet I might just rename the type to a custom Type to comply with the docs - just in case. 

I need to roll a bugfix anyway.

Thanks for bringing this to my attention.

**Comment by dragon7307** [comment]
I internally changed the namespace to SpanExtensions. Should be resolved.
